PROTO_DIR := proto/upload_service/v1

PROTO_FILE := $(PROTO_DIR)/upload_service.proto

OUT_DIR := ./gen/go/upload_service/v1

all: generate_v1

$(OUT_DIR):
	mkdir -p $(OUT_DIR)

generate_v1: $(OUT_DIR)
	protoc --go_out=$(OUT_DIR) --go-grpc_out=$(OUT_DIR) $(PROTO_FILE)

clean:
	rm -f $(OUT_DIR)/*.go

.PHONY: all generate clean

.PHONY: all generate clean
